title: Josh Zhanson
email: josh@jzhanson.com
description: >
  Josh Zhanson's personal website
baseurl: ""
url: "http://jzhanson.com" # the base hostname & protocol for your site
github_username: jzhanson

markdown: kramdown
